export const KURAN_TESTI_PEYGAMBER_SORULARI = [
  {
    id: 255,
    category: 'Peygamberler Tarihi',
    question: 'Hz. Âdem ve eşinin yasak ağaca yaklaşmalarından sonra başlayan dönüş süreci, Bakara ve A‘râf sureleri birlikte değerlendirildiğinde hangi ifadeyle en doğru biçimde açıklanır?',
    options: ['Allah’tan öğrendikleri tevbe sözleriyle hatalarını kabul etmiş, bağışlanma ve merhamet dilemişler; Allah da tevbelerini kabul etmiştir', 'Yaptıklarında hiçbir sorumluluk görmeyip hatayı bütünüyle meleklere yüklemişlerdir', 'Dünyaya gönderilmemek için yalnız geçmiş nimetlerin geri verilmesini istemişlerdir', 'Bağışlanma dilemeden yalnız kendi çabalarıyla eski konumlarına dönebileceklerini düşünmüşlerdir'],
    correctIndex: 0,
    explanation: 'Bakara 37, Hz. Âdem’in Rabbinden bazı sözler aldığını ve tevbesinin kabul edildiğini bildirir. A‘râf 23 bu sözlerin özünü, kişinin kendi yanlışını kabul ederek Allah’ın bağışlama ve rahmetine sığınması şeklinde verir.',
    reference: 'Bakara 2/37; A‘râf 7/23',
  },
  {
    id: 256,
    category: 'Kıssa Ayrıntısı',
    question: 'Tâhâ suresinde Hz. Âdem’in yasak ağaçla ilgili imtihanından önce verilen söz ve sonrasındaki davranışı hangi insanî zaaf üzerinden anlatılır?',
    options: ['Kendisine daha önce kesin bir buyruk verilmiş olmasına rağmen onu unutması ve yeterli kararlılığı gösterememesi üzerinden', 'Kendisine hiçbir uyarı yapılmadığı hâlde bilmediği bir emirden sorumlu tutulması üzerinden', 'Meleklerin yönlendirmesiyle bilinçli biçimde Allah’a ortak koşması üzerinden', 'Yeryüzüne inmeyi önceden planlayarak ağaca yalnız bu amaçla yaklaşması üzerinden'],
    correctIndex: 0,
    explanation: 'Tâhâ 115’te Hz. Âdem’den daha önce söz alındığı, fakat onun unuttuğu ve kendisinde yeterli kararlılık bulunmadığı ifade edilir. Kıssa insanın unutma ve irade zayıflığına karşı ilahi uyarıya bağlı kalması gerektiğini gösterir.',
    reference: 'Tâhâ 20/115-123',
  },
  {
    id: 257,
    category: 'Kıssa Muhakemesi',
    question: 'Hz. Nuh tufan sonrasında boğulan oğlunun ailesinden olduğunu söyleyerek Allah’a yöneldiğinde aldığı cevap, kurtuluşta soy bağı ile iman arasındaki ilişkiyi nasıl açıklar?',
    options: ['Oğlunun yaptığı kötü davranış nedeniyle iman ailesinin bir üyesi sayılmadığını, hakkında bilgi bulunmayan şeyi istememesi gerektiğini bildirir', 'Peygamber çocuğu olmanın iman ve davranıştan bağımsız olarak kesin kurtuluş sağlayacağını bildirir', 'Tufanda ölen herkesin daha sonra dünyaya dönerek yeniden sınanacağını bildirir', 'Aile bağının ilahi hükümden üstün olduğunu ve oğlunun mutlaka kurtarılacağını bildirir'],
    correctIndex: 0,
    explanation: 'Hud 45-47’de Hz. Nuh’un talebi üzerine oğlunun kötü bir iş ortaya koyduğu ve iman temelli aileden olmadığı açıklanır. Hz. Nuh da bilgisi olmayan şeyi istemekten Allah’a sığınarak bağışlanma diler.',
    reference: 'Hud 11/45-47',
  },
  {
    id: 258,
    category: 'Kıssa Ayrıntısı',
    question: 'Tufanın başladığını gösteren işaret ortaya çıktığında Hz. Nuh’a gemiye kimleri alması emredilmiş, bu emrin kapsamına hangi istisna getirilmiştir?',
    options: ['Her canlıdan birer çift, haklarında hüküm verilmemiş aile fertleri ve iman edenler alınmış; daha önce aleyhlerinde hüküm verilmiş olanlar dışarıda bırakılmıştır', 'Yalnız kendi çocukları ve toplumun zenginleri alınmış; diğer canlılar gemiye kabul edilmemiştir', 'Sadece iman eden insanlar alınmış; hayvanların tufandan kendiliğinden kurtulacağı bildirilmiştir', 'Kavmin tamamı hiçbir inanç ayrımı yapılmadan gemiye alınmış; peygamber ailesi dışarıda bırakılmıştır'],
    correctIndex: 0,
    explanation: 'Hud 40’ta ilahi işaret belirdiğinde her türden birer çiftin, haklarında önceki hüküm bulunmayan aile fertlerinin ve iman edenlerin gemiye alınması emredilir. Ayet aynı zamanda Hz. Nuh’a çok az kişinin iman ettiğini belirtir.',
    reference: 'Hud 11/40-43',
  },
  {
    id: 259,
    category: 'Peygamberlerin Tavrı',
    question: 'Hz. Hud, Âd kavminin tehdit ve suçlamaları karşısında tebliğinin karşılıksızlığını ve Allah’a güvenini hangi gerekçelerle savunmuştur?',
    options: ['Ücretini yalnız Allah’tan beklediğini, kendi Rabbi ve onların Rabbi olan Allah’a dayandığını ve her canlının O’nun hâkimiyeti altında bulunduğunu söylemiştir', 'Kavminden siyasi iktidar ve düzenli vergi istediğini, bunlar verilirse tebliği bırakacağını söylemiştir', 'Putların bir bölümünü kabul ederek kavmiyle ortak bir ibadet düzeni kurmayı önermiştir', 'Yalnız kendi ailesinin korunması şartıyla toplumun yanlışlarına sessiz kalmayı kabul etmiştir'],
    correctIndex: 0,
    explanation: 'Hud 50-56’da Hz. Hud, tebliğine karşılık ücret istemediğini ve Allah’a tevekkül ettiğini açıklar. Kavmin yüz çevirmesi hâlinde bile mesajı ulaştırdığını, Allah’ın başka bir toplum getirmeye güç yetireceğini bildirir.',
    reference: 'Hud 11/50-57',
  },
  {
    id: 260,
    category: 'Kıssa Ayrıntısı',
    question: 'Neml suresinde Hz. Salih’in şehrinde bozgunculuk yapan dokuz kişilik grubun gece planı ve bu plana karşı gerçekleşen ilahi karşılık hangisidir?',
    options: ['Salih’i ve ailesini gece öldürüp yakınlarına olaydan habersiz olduklarını söylemeyi planlamışlar; kurdukları tuzak kendileri fark etmeden boşa çıkarılmıştır', 'Deveyi koruyup bütün kavmi tevhide çağırmayı planlamışlar; bunun üzerine şehirden sürülmüşlerdir', 'Şehri terk ederek başka bir peygambere katılmayı planlamışlar; yolları denizle kesilmiştir', 'Hz. Salih’ten özür dileyip mallarını yoksullara dağıtmayı planlamışlar; fakat kavimleri buna izin vermemiştir'],
    correctIndex: 0,
    explanation: 'Neml 48-53, şehirde düzeltme yapmayan dokuz kişilik bir grubun Hz. Salih ve ailesine gece baskını planladığını anlatır. Allah onların tuzağına karşılık vermiş, kendilerini ve toplumlarını helake uğratırken iman edip sakınanları kurtarmıştır.',
    reference: 'Neml 27/45-53',
  },
  {
    id: 261,
    category: 'İman ve Delil',
    question: 'Hz. İbrahim ölülerin nasıl diriltildiğini görmek istediğinde Allah’ın dört kuşla yaptırdığı uygulamanın amacı ve sonucu nasıl açıklanmalıdır?',
    options: ['İbrahim zaten iman ettiğini söylemiş; uygulama kalbinin iyice tatmin olması için yapılmış ve parçalanan kuşların çağrılınca hızla gelmesiyle diriliş gösterilmiştir', 'İbrahim dirilişi kesin biçimde reddettiği için peygamberliği sona erdirilmiş ve kuşlar ona verilmemiştir', 'Uygulama yalnız kuşların yön bulma yeteneğini ölçmüş, ahiret ve dirilişle hiçbir ilişki kurmamıştır', 'Kuşların yeniden gelmesi İbrahim’in bağımsız yaratma gücüne sahip olduğunu kanıtlamak için gerçekleştirilmiştir'],
    correctIndex: 0,
    explanation: 'Bakara 260’ta Hz. İbrahim iman etmediği için değil, kalbinin huzur bulması için dirilişin nasıl gerçekleştiğini görmek istediğini belirtir. Kuşlarla yapılan uygulama diriltme kudretinin yalnız Allah’a ait olduğunu somutlaştırır.',
    reference: 'Bakara 2/260',
  },
  {
    id: 262,
    category: 'Tevhid Muhakemesi',
    question: 'En‘âm suresinde Hz. İbrahim’in yıldız, ay ve güneş üzerinden yürüttüğü düşünme sürecinin ulaştığı tevhid sonucu hangisidir?',
    options: ['Batıp kaybolan varlıkların ilah olamayacağını göstererek yüzünü gökleri ve yeri yaratana çevirdiğini ve ortak koşanlardan olmadığını ilan etmiştir', 'En parlak gök cisminin diğerlerinden daha uzun göründüğü için kesinlikle ilah olduğunu kabul etmiştir', 'Yıldız, ay ve güneşin ilahi yetkiyi kendi aralarında paylaştıkları sonucuna ulaşmıştır', 'Gök cisimlerinin hareketlerinden hiçbir yaratıcı fikrine ulaşılamayacağını ve düşünmenin gereksiz olduğunu söylemiştir'],
    correctIndex: 0,
    explanation: 'En‘âm 75-79’daki anlatım, kavmin gök cisimlerine yüklediği ilahlık düşüncesini onların batıp kaybolması üzerinden çürütür. Hz. İbrahim değişen varlıkları değil, gökleri ve yeri yoktan yaratmış olan Allah’ı yönelişinin merkezi yapar.',
    reference: 'En‘âm 6/74-79',
  },
  {
    id: 263,
    category: 'Kıssa Ayrıntısı',
    question: 'Hz. İbrahim’e insan görünümünde gelen elçilerle ilgili olayda, onun korkusunun sebebi ve ardından verilen iki haber hangi seçenekte doğru sıralanmıştır?',
    options: ['İkram ettiği kızarmış buzağıya ellerini uzatmamaları onu korkutmuş; elçiler Lut kavmine gönderildiklerini ve İshak ile ardından Yakub’u müjdelediklerini açıklamıştır', 'Misafirlerin çok yemek yemeleri onu korkutmuş; Nuh tufanının başlayacağını ve İsmail’in Mısır’a gideceğini bildirmişlerdir', 'Misafirlerin silahlı gelmeleri onu korkutmuş; bütün kavminin hemen iman edeceğini ve hiçbir azap yaşanmayacağını söylemişlerdir', 'İkramını yetersiz bulmaları onu korkutmuş; kendisinin hükümdar, eşinin de toplumun yöneticisi olacağını müjdelemişlerdir'],
    correctIndex: 0,
    explanation: 'Hud 69-73’te elçiler ikrama el uzatmayınca Hz. İbrahim kaygılanır. Onlar korkmamasını, Lut kavmine gönderildiklerini söyler; eşi de İshak ve onun ardından Yakub ile müjdelenir.',
    reference: 'Hud 11/69-76; Zariyat 51/24-30',
  },
  {
    id: 264,
    category: 'Kıssa Bağlamı',
    question: 'Elçiler Hz. Lut’a gerçek görevlerini açıkladıklarında ailesinin şehirden çıkarılması ve azabın zamanı hakkında hangi talimatı vermişlerdir?',
    options: ['Gecenin bir bölümünde ailesini yola çıkarmasını, kimsenin arkasına bakmamasını, eşi dışında herkesin ilerlemesini ve belirlenen vaktin sabah olduğunu bildirmişlerdir', 'Gündüz vakti bütün kavmiyle birlikte şehir meydanında beklemesini ve azabın yıllar sonra geleceğini söylemişlerdir', 'Ailesini şehirde bırakıp tek başına dağa çıkmasını ve eşinin herkesten önce kurtulacağını bildirmişlerdir', 'Kavmine son bir ay süre verildiğini, bu sürede bütün evlerini terk etmelerine gerek olmadığını söylemişlerdir'],
    correctIndex: 0,
    explanation: 'Hicr 61-66 ve Hud 81’de elçiler Hz. Lut’a gecenin bir bölümünde ailesini çıkarmasını, arkaya bakmadan emredilen yere ilerlemelerini bildirir. Eşi kurtulacakların dışında tutulur ve azabın vaktinin sabah olduğu açıklanır.',
    reference: 'Hicr 15/61-66; Hud 11/77-83',
  },
  {
    id: 265,
    category: 'Peygamberlerin Özellikleri',
    question: 'Meryem suresinde Hz. İsmail’in “sözünde duran bir kimse” olarak anılmasının ardından peygamberlik görevini tamamlayan hangi ailevi ve ibadi yönü vurgulanır?',
    options: ['Ailesine namazı ve zekâtı emrettiği, Rabbinin katında hoşnutluk kazanmış bir elçi ve peygamber olduğu vurgulanır', 'Ailesini ibadetlerden uzak tuttuğu ve yalnız kişisel tefekkürü yeterli gördüğü vurgulanır', 'Toplumundan ücret aldığı ve tebliğini sadece zengin ailelerle sınırladığı vurgulanır', 'Söz vermekten kaçındığı ve aile sorumluluğunu başka kişilere bıraktığı vurgulanır'],
    correctIndex: 0,
    explanation: 'Meryem 54-55, Hz. İsmail’i sözünde duran, elçi ve peygamber olan biri şeklinde tanıtır. Onun ailesine namazı ve zekâtı emretmesi, peygamberlik örnekliğinin aile içindeki sorumluluğu da kapsadığını gösterir.',
    reference: 'Meryem 19/54-55',
  },
  {
    id: 266,
    category: 'Kıssa Ayrıntısı',
    question: 'Hz. Yusuf’un gömleğinin babası Hz. Yakub’a ulaştırılmasıyla gerçekleşen olaylar hangi sırayla anlatılır?',
    options: ['Yusuf gömleğinin babasının yüzüne konulmasını ister; müjdeci gelmeden Yakub Yusuf’un kokusunu aldığını söyler ve gömlek yüzüne konunca gözleri yeniden görür', 'Yakub önce Mısır’a gider, Yusuf’un gömleğini satın alır ve yıllar sonra oğlunun yaşadığını öğrenir', 'Kardeşler gömleği gizler, Yakub hiçbir haber almadan kendiliğinden görmeye başlar ve Yusuf Mısır’dan ayrılır', 'Yusuf gömleğini hükümdara verir, hükümdar da onu Yakub’a göndermeden önce bütün kardeşleri cezalandırır'],
    correctIndex: 0,
    explanation: 'Yusuf 93-96’da Hz. Yusuf gömleğini babasının yüzüne koymalarını ve ailesini getirmelerini ister. Kafile ayrılınca Hz. Yakub Yusuf’un kokusunu aldığını belirtir; müjdeci gömleği yüzüne koyunca gözleri açılır.',
    reference: 'Yusuf 12/93-98',
  },
  {
    id: 267,
    category: 'Kıssa Muhakemesi',
    question: 'Hz. Yusuf’un hapishanedeki iki arkadaşının rüyalarına yaptığı yorum, onların geleceği bakımından hangi iki farklı sonucu ve hangi ek talebi içerir?',
    options: ['Birinin efendisine şarap sunmaya döneceğini, diğerinin asılacağını söylemiş; kurtulacağını düşündüğü kişiden hükümdarın yanında kendisini anmasını istemiştir', 'Her ikisinin de aynı gün serbest kalacağını söylemiş; ikisinden de ailesine para göndermelerini istemiştir', 'Birinin hükümdar, diğerinin ordu komutanı olacağını söylemiş; hapishaneden zorla çıkarılmasını istemiştir', 'Rüyaların yorumlanamayacağını söylemiş; arkadaşlarından tebliğini gizlemelerini istemiştir'],
    correctIndex: 0,
    explanation: 'Yusuf 36-42’de Hz. Yusuf önce tevhid mesajını açıklar, sonra bir arkadaşının yeniden içki sunacağını, diğerinin asılacağını bildirir. Kurtulacağını düşündüğü kişiden hükümdarın yanında kendisini anmasını ister; fakat o kişi bunu bir süre unutur.',
    reference: 'Yusuf 12/36-42',
  },
  {
    id: 268,
    category: 'Kıssa Ayrıntısı',
    question: 'Hz. Yusuf’un öz kardeşini yanında tutabilmesi için su kabının yüküne yerleştirilmesinden sonra uygulanan hukukî süreç neden Mısır kralının kanunundan farklı bir sonuca ulaşmıştır?',
    options: ['Kardeşlere kayıp eşyanın cezası sorulmuş, onların kendi hukuklarına göre eşya kimin yükünde çıkarsa onun alıkonulacağını söylemeleri Yusuf’un kardeşini yanında tutmasına imkân vermiştir', 'Mısır kanunu hırsızlıkla suçlanan herkesi köle yaptığı için bütün kardeşler kalıcı olarak alıkonulmuştur', 'Yusuf hiçbir arama yapmadan kardeşini seçmiş ve kanunların tamamını açıkça yürürlükten kaldırmıştır', 'Su kabı başka bir kardeşin yükünde bulunduğu hâlde hükümdar öz kardeşin tutulmasını emretmiştir'],
    correctIndex: 0,
    explanation: 'Yusuf 70-76’da tas kardeşinin yüküne konur. Kardeşler cezanın, eşya kimin yükünde bulunursa onun alıkonulması olduğunu kendileri söyler. Ayet, kralın kanununa göre Yusuf’un kardeşini bu biçimde tutamayacağını ve planın Allah’ın öğretmesiyle gerçekleştiğini belirtir.',
    reference: 'Yusuf 12/70-76; Diyanet Kur’an Yolu Tefsiri',
  },
  {
    id: 269,
    category: 'Kıssa Ayrıntısı',
    question: 'Hz. Eyyub’un bir konuda ettiği yemini yerine getirirken eşine zarar vermemesini sağlayan ilahi kolaylık Sad suresinde nasıl gösterilmiştir?',
    options: ['Eline bir demet sap alıp onunla bir kez vurması ve böylece yeminini bozmamış sayılması emredilmiştir', 'Yeminini yerine getirmek için ailesinden bütünüyle ayrılması ve bir daha dönmemesi emredilmiştir', 'Bütün yeminlerin sonuçsuz olduğu söylenerek hiçbir sorumluluk taşımadığı bildirilmiştir', 'Yeminini başka bir kişiye devrederek onun uygulamasını istemesi emredilmiştir'],
    correctIndex: 0,
    explanation: 'Sad 44’te Hz. Eyyub’a bir demet sapla bir kez vurması, böylece yeminini bozmaması ve ağır bir zarar vermemesi öğretilir. Ayet onu sabırlı, güzel bir kul ve Allah’a yönelen biri olarak över.',
    reference: 'Sad 38/41-44',
  },
  {
    id: 270,
    category: 'Tebliğ ve Toplum',
    question: 'Medyen halkı Hz. Şuayb’ın namazı ile ekonomik eleştirileri arasında nasıl bir ilişki kurmuş, Hz. Şuayb buna hangi ahlaki ilkeyle cevap vermiştir?',
    options: ['Namazının atalarının taptıklarını ve mallarında diledikleri gibi davranmayı bırakmalarını mı emrettiğini sormuşlar; o ise yasakladığı şeyi kendisinin yapmak istemediğini ve gücü ölçüsünde ıslah amaçladığını söylemiştir', 'Namazının daha fazla mal biriktirmeyi emrettiğini düşünmüşler; o da yalnız zenginlerin ibadetle sorumlu olduğunu söylemiştir', 'Ticaretle dinin hiçbir ilişkisi olmadığını savunmuşlar; o da ölçü ve tartıdaki hileyi serbest bıraktığını açıklamıştır', 'Kendisinden hükümdar olmasını istemişler; o da bütün ekonomik kararları tek başına vermeyi kabul etmiştir'],
    correctIndex: 0,
    explanation: 'Hud 87-88’de kavmi Hz. Şuayb’ın namazının geleneksel putları ve ekonomik serbestliklerini sınırlamasını alaya alır. Şuayb, söylediğinin tersini yapmayacağını, yalnız düzeltmek istediğini ve başarısının Allah’a bağlı olduğunu açıklar.',
    reference: 'Hud 11/84-88',
  },
  {
    id: 271,
    category: 'Kıssa Bağlamı',
    question: 'Hz. Musa’nın annesine verilen ilhamdan çocuğun yeniden kendisine dönmesine kadar gelişen olayların doğru sıralaması hangisidir?',
    options: ['Onu emzirmesi, korkunca nehre bırakması, ablasının uzaktan izlemesi, Musa’nın başka sütanneleri kabul etmemesi ve sonunda annesine geri verilmesi', 'Onu saraya kendi eliyle götürmesi, Firavun’dan ücret istemesi, ablasının sarayda kalması ve Musa’nın annesini reddetmesi', 'Çocuğu çöle bırakması, bir kervanın bulması, yıllarca başka ülkede yaşaması ve yetişkin olarak annesine dönmesi', 'Önce Firavun’un iman etmesi, sonra Musa’nın nehre bırakılması ve annesinin saray yöneticisi olması'],
    correctIndex: 0,
    explanation: 'Kasas 7-13’te Musa’nın annesine onu emzirmesi ve korktuğunda nehre bırakması ilham edilir. Ablası uzaktan izler; Musa başka sütanneleri kabul etmeyince ablasının önerisiyle annesine kavuşur. Böylece annenin gözü aydın olur ve Allah’ın vaadinin gerçekliğini bilir.',
    reference: 'Kasas 28/7-13; Diyanet Kur’an Yolu Tefsiri',
  },
  {
    id: 272,
    category: 'Kıssa Ayrıntısı',
    question: 'Hz. Musa Medyen suyunda iki kadına yardım ettikten sonra gelişen süreç, onun güvenilirliği ve evliliği bakımından nasıl ilerlemiştir?',
    options: ['Kadınlardan biri onu haya ile babasına çağırmış, güçlü ve güvenilir olduğu belirtilmiş; Musa belirli süre çalışması karşılığında iki kızdan biriyle evlenme teklifini kabul etmiştir', 'Kadınlar yardımını reddetmiş, Musa şehri terk etmiş ve onlarla bir daha karşılaşmamıştır', 'Musa sürüyü kendisine almış, bunun karşılığında şehrin yönetimini üstlenmiş ve evlilik teklifini reddetmiştir', 'Kadınların babası Musa’dan ücret istemiş, Musa da Mısır’a dönerek anlaşmayı bozmuştur'],
    correctIndex: 0,
    explanation: 'Kasas 23-28’de Hz. Musa kadınların hayvanlarını suladıktan sonra Allah’ın vereceği hayra muhtaç olduğunu dile getirir. Kadınlardan biri onu babasına çağırır; güçlü ve güvenilir oluşu vurgulanır ve sekiz, isterse on yıllık çalışma karşılığında evlilik anlaşması yapılır.',
    reference: 'Kasas 28/23-28',
  },
  {
    id: 273,
    category: 'Derinlikli Kıssa Okuması',
    question: 'Hz. Musa ile Allah’ın rahmet ve özel bilgi verdiği kulun yolculuğundaki gemi, genç ve duvar olaylarının açıklamaları hangi seçenekte doğru eşleştirilmiştir?',
    options: ['Gemi zorba kralın sağlam gemileri gasbetmesinden korunmuş, gencin yerine ailesine daha temiz bir evlat verilmesi istenmiş, duvarın altındaki yetimlere ait hazine büyüyene kadar korunmuştur', 'Gemi sahiplerinden intikam için delinmiş, genç hiçbir gerekçe olmadan cezalandırılmış, duvar yalnız ücret alınabilmesi için onarılmıştır', 'Gemi tamamen batırılmış, genç başka ülkeye gönderilmiş, duvarın altındaki hazine yolcular arasında paylaşılmıştır', 'Üç olay da Musa’nın bilgiyi reddetmesi nedeniyle ortaya çıkmış ve hiçbirinin ilahi hikmetle ilişkisi kurulmamıştır'],
    correctIndex: 0,
    explanation: 'Kehf 79-82 olayların görünen yüzünün arkasındaki gerekçeleri açıklar. Gemi yoksulların malını gasptan, duvar yetimlerin hazinesini erken kayıptan korur; gençle ilgili olayın da anne babayı azgınlık ve inkâra sürükleme tehlikesiyle bağlantılı olduğu ve bunların kişisel kararla yapılmadığı bildirilir.',
    reference: 'Kehf 18/60-82; Diyanet Kur’an Yolu Tefsiri',
  },
  {
    id: 274,
    category: 'İman Cesareti',
    question: 'Firavun’un sihirbazları Hz. Musa’nın mucizesi karşısında iman ettikten sonra el ve ayaklarını çaprazlama kesme ve asma tehdidine nasıl cevap vermişlerdir?',
    options: ['Açık deliller ve kendilerini yaratan Allah karşısında Firavun’u tercih etmeyeceklerini, onun hükmünün yalnız dünya hayatında geçerli olduğunu söylemişlerdir', 'Canlarını kurtarmak için imanlarından hemen döndüklerini ve Musa’yı suçladıklarını açıklamışlardır', 'Firavun’un kendilerini bağışlaması karşılığında mucizeyi sihir olarak nitelemeyi kabul etmişlerdir', 'Yalnız daha fazla ücret verilirse eski dinlerinde kalacaklarını söylemişlerdir'],
    correctIndex: 0,
    explanation: 'Tâhâ 70-73’te sihirbazlar secdeye kapanarak Harun ve Musa’nın Rabbine iman eder. Firavun’un ağır tehdidine karşı onun yalnız dünya hayatında hükmedebileceğini, Allah’ın daha hayırlı ve daha kalıcı olduğunu bildirirler.',
    reference: 'Tâhâ 20/70-76; A‘râf 7/120-126',
  },
  {
    id: 275,
    category: 'Kıssa Muhakemesi',
    question: 'Hz. Musa buzağıya yönelen kavmine döndüğünde kardeşi Hz. Harun’u sorgulamış, Hz. Harun ise neden daha sert bir müdahale yapmadığını nasıl açıklamıştır?',
    options: ['Kavmin kendisini güçsüz bırakıp neredeyse öldüreceğini ve Musa’nın “İsrailoğulları arasını böldün, sözümü tutmadın” demesinden çekindiğini belirtmiştir', 'Buzağıya tapmayı doğru bulduğu için kavme katıldığını ve Musa’nın da bunu kabul etmesini istediğini söylemiştir', 'Kavmin tamamının imanını koruduğunu, ortada hiçbir sapma bulunmadığını ileri sürmüştür', 'Musa’nın dönüşünü istemediği için kavmi bilerek buzağıya yönlendirdiğini açıklamıştır'],
    correctIndex: 0,
    explanation: 'A‘râf 150’de Hz. Harun kavmin kendisini güçsüz bıraktığını ve öldürmeye yaklaştığını söyler. Tâhâ 92-94’te ise ayrılık çıkarmak ve Musa’nın sözünü tutmamakla suçlanmaktan çekindiğini belirtir. Bu, onun sapmayı onayladığı anlamına gelmez.',
    reference: 'A‘râf 7/150-151; Tâhâ 20/90-94',
  },
  {
    id: 276,
    category: 'Adalet ve Tevbe',
    question: 'Hz. Davud’a ansızın giren iki davacının koyunlar hakkındaki anlaşmazlığı, karar verme ve tevbe bakımından hangi dersi ortaya koymuştur?',
    options: ['Davud tek tarafın anlatımından haksızlığı fark etmiş, olayın kendisi için bir sınama olduğunu anlayınca bağışlanma dileyip secde ederek Allah’a yönelmiştir', 'Davud tarafları hiç dinlemeden ikisini de cezalandırmış ve kararının sorgulanamayacağını söylemiştir', 'Davacılar gerçek bir savaş başlatmış, Davud da krallığını bırakarak şehirden ayrılmıştır', 'Çok koyunu olanın her durumda haklı olduğuna karar vermiş ve yoksul tarafın hakkını reddetmiştir'],
    correctIndex: 0,
    explanation: 'Sad 21-25’te birinin doksan dokuz, diğerinin bir koyunu olduğu davada güçlü tarafın tek koyunu da istemesi haksızlık olarak değerlendirilir. Hz. Davud olayın bir imtihan olduğunu anlayarak Rabbinden bağışlanma diler ve yönelir.',
    reference: 'Sad 38/21-26',
  },
  {
    id: 277,
    category: 'Peygamberler Tarihi',
    question: 'Talut’un ordusuyla Calut’un ordusu karşılaştığında Hz. Davud’un kıssadaki rolü ve sonrasında kendisine verilenler nasıl anlatılır?',
    options: ['Davud Calut’u öldürmüş, Allah ona hükümdarlık ve hikmet vermiş ve dilediği bilgilerden öğretmiştir', 'Davud savaşa katılmayı reddetmiş, daha sonra yalnız bir tüccar olarak yaşamıştır', 'Calut Davud’u yenmiş, fakat Talut onu başka bir ülkenin yöneticisi yapmıştır', 'Davud yalnız ordunun su ihtiyacını karşılamış, peygamberlik ve hikmetle ilişkilendirilmemiştir'],
    correctIndex: 0,
    explanation: 'Bakara 251, Allah’ın izniyle ordunun Calut kuvvetlerini yendiğini ve Davud’un Calut’u öldürdüğünü bildirir. Ardından Allah’ın Davud’a hükümdarlık ve hikmet verdiği, ona dilediği şeyleri öğrettiği belirtilir.',
    reference: 'Bakara 2/249-251',
  },
  {
    id: 278,
    category: 'Şükür ve Yönetim',
    question: 'Hz. Süleyman’ın ordusu karıncalar vadisine geldiğinde bir karıncanın uyarısını işitmesi, onun hangi duasına ve yönetim ahlakına dönüşmüştür?',
    options: ['Gülümseyerek Allah’ın kendisine ve anne babasına verdiği nimete şükretmeyi, Allah’ın razı olacağı işler yapmayı ve salih kullar arasına katılmayı istemiştir', 'Karıncaların bulunduğu bölgenin tamamen boşaltılmasını ve bütün canlıların ordusuna hizmet etmesini emretmiştir', 'Bu yeteneği kendi bağımsız gücü sayarak hiçbir şükür ifadesinde bulunmamıştır', 'Ordusunu dağıtıp hükümdarlığı bırakmasını sağlayacak bir işaret olarak değerlendirmiştir'],
    correctIndex: 0,
    explanation: 'Neml 18-19’da karınca diğerlerini yuvalarına girmeleri için uyarır. Hz. Süleyman bu söze gülümser ve nimetin şükrünü, Allah’ın razı olacağı salih ameli ve rahmetle iyi kullar arasına katılmayı diler.',
    reference: 'Neml 27/17-19',
  },
  {
    id: 279,
    category: 'İlim ve Şükür',
    question: 'Sebe melikesinin tahtının Hz. Süleyman’a getirilmesi sırasında “kitaptan bilgisi olan kişi”nin başarısı, Hz. Süleyman tarafından nasıl yorumlanmıştır?',
    options: ['Taht göz açıp kapayıncaya kadar gelince bunu Rabbinin bir lütfu ve şükredip şükretmeyeceğini sınayan bir imtihan olarak görmüştür', 'Tahtın gelişini yalnız kendi askerî gücünün kanıtı saymış ve Allah’ın lütfuyla hiçbir bağ kurmamıştır', 'Tahtı getiren kişiyi ülkesinden çıkarmış ve tahtın geri gönderilmesini emretmiştir', 'Bu olaydan sonra bütün insanların kendisine ibadet etmesini istemiştir'],
    correctIndex: 0,
    explanation: 'Neml 38-40’ta güçlü bir cin tahtı getirmeyi teklif eder; kitaptan bilgisi olan kişi ise onu göz açıp kapamadan getirir. Hz. Süleyman sonucu Allah’ın lütfu ve şükür sınavı olarak değerlendirir; şükrün kişinin kendi yararına olduğunu söyler.',
    reference: 'Neml 27/38-40',
  },
  {
    id: 280,
    category: 'Tevhid Mücadelesi',
    question: 'Kur’an’da Hz. İlyas’ın kavmine yönelttiği temel eleştiri, Ba‘l adlı put ile Allah arasında nasıl bir karşılaştırma kurar?',
    options: ['En güzel yaratan Allah’ı bırakıp Ba‘l’e yalvarmalarını sorgular ve Allah’ın onların da önceki atalarının da Rabbi olduğunu hatırlatır', 'Ba‘l’e ibadetin yalnız belirli günlerde yapılmasını, diğer günlerde Allah’a yönelmelerini önerir', 'Putun Allah’la aynı yetkilere sahip olduğunu ve iki ibadetin birlikte sürdürülebileceğini söyler', 'Kavmin yalnız ekonomik düzenini eleştirir, inançları hakkında hiçbir değerlendirme yapmaz'],
    correctIndex: 0,
    explanation: 'Saffat 123-132’de Hz. İlyas kavmine Allah’a karşı sorumluluklarını, Ba‘l’e yalvarıp en güzel yaratıcıyı bırakmalarını sorgular. Onun seçkin kullardan olduğu ve sonraki nesiller arasında iyi anıldığı bildirilir.',
    reference: 'Saffat 37/123-132',
  },
  {
    id: 281,
    category: 'Peygamber Bilgisi',
    question: 'Kur’an’da hayat hikâyesi ayrıntılı anlatılmayan Hz. Elyesa hakkında doğrudan verilen değerlendirmeler hangi seçenekte doğru toplanmıştır?',
    options: ['İsmail ve Yunus’la birlikte âlemlere üstün kılınanlar arasında; İsmail ve Zülkifl’le birlikte seçkin iyi kimseler arasında anılmıştır', 'Firavun’a gönderilen iki kardeş peygamberden biri olduğu ve denizi yardığı ayrıntılı biçimde anlatılmıştır', 'Sebe ülkesini yönettiği ve kuşların dilini bildiği açıkça bildirilmiştir', 'Kavmi tarafından ateşe atıldığı ve ateşin kendisine serin kılındığı anlatılmıştır'],
    correctIndex: 0,
    explanation: 'En‘âm 86’da Elyesa, İsmail, Yunus ve Lut’la beraber âlemlere üstün kılınanlar arasında sayılır. Sad 48’de ise İsmail ve Zülkifl’le birlikte seçkin ve iyi kimselerden olduğu belirtilir; Kur’an ayrıntılı bir kıssa vermez.',
    reference: 'En‘âm 6/86; Sad 38/48',
  },
  {
    id: 282,
    category: 'Peygamber Bilgisi',
    question: 'Hz. Zülkifl’in Kur’an’daki sınırlı fakat açık tanıtımı, onun hangi ahlaki gruplar içinde yer aldığını gösterir?',
    options: ['İsmail ve İdris’le birlikte sabredenlerden, ayrıca seçkin ve iyi kimselerden olduğu bildirilir', 'Kavmine ölçü ve tartıyı öğretip Medyen’de yaşayan tek hükümdar olduğu bildirilir', 'Babasıyla Kâbe’yi inşa ettiği ve kurban imtihanına katıldığı ayrıntılı biçimde anlatılır', 'Balığın içinde dua ettiği ve yüz bin kişilik kavme gönderildiği bildirilir'],
    correctIndex: 0,
    explanation: 'Enbiya 85-86’da İsmail, İdris ve Zülkifl’in sabredenlerden olduğu ve rahmete alındıkları belirtilir. Sad 48 de onu İsmail ve Elyesa ile birlikte seçkin iyi kimseler arasında anar.',
    reference: 'Enbiya 21/85-86; Sad 38/48',
  },
  {
    id: 283,
    category: 'Kıssa Sıralaması',
    question: 'Saffat suresine göre Hz. Yunus’un görev yerinden ayrılmasından yeniden kavmine gönderilmesine kadar olayların doğru sırası hangisidir?',
    options: ['Dolu gemiye kaçmış, kura sonucu denize atılmış, balık tarafından yutulmuş, tesbih edenlerden olduğu için kurtarılmış, kıyıda bitkiyle gölgelenmiş ve kalabalık bir topluma gönderilmiştir', 'Önce kavmi iman etmiş, sonra gemiye binmiş, hiçbir tehlike yaşamadan başka bir ülkenin hükümdarı olmuştur', 'Balık onu karada yutmuş, gemidekiler kurtarmış ve kendi isteğiyle peygamberlik görevini sona erdirmiştir', 'Kura kendisine çıkmadığı hâlde denize atlamış, balığın içinde hiç dua etmeden uzun yıllar kalmıştır'],
    correctIndex: 0,
    explanation: 'Saffat 139-148 olayları gemi, kura, balık, tesbih sayesinde kurtuluş, çıplak kıyıya bırakılma, geniş yapraklı bitki ve yüz bin ya da daha fazla kişiye gönderilme sırasıyla anlatır. Enbiya 87-88 duasının tevhid ve itiraf içeriğini verir.',
    reference: 'Saffat 37/139-148; Enbiya 21/87-88',
  },
  {
    id: 284,
    category: 'Kıssa Ayrıntısı',
    question: 'Hz. Zekeriyya yaşlılığına rağmen çocukla müjdelendiğinde istediği işaret nedir ve bu işaret gerçekleşirken kendisine hangi ibadet tavsiye edilmiştir?',
    options: ['Sağlıklı olduğu hâlde üç gün insanlarla yalnız işaretle konuşabilmesi; Rabbini çok anması ve sabah akşam tesbih etmesi', 'Üç ay boyunca hiç uyumaması; yalnız gece vakti yolculuk yapması', 'Elindeki asanın yılana dönüşmesi; kavmini şehirden çıkarması', 'Güneşin üç gün doğmaması; bütün malını dağıtması'],
    correctIndex: 0,
    explanation: 'Âl-i İmran 41’de işaret, sağlıklı olduğu hâlde üç gün insanlarla konuşamamak olarak verilir; Allah’ı çok anması ve tesbih etmesi istenir. Meryem 10’da bu süre üç gece şeklinde ifade edilir.',
    reference: 'Âl-i İmran 3/38-41; Meryem 19/7-11',
  },
  {
    id: 285,
    category: 'Peygamberlerin Özellikleri',
    question: 'Meryem suresinde çocuk yaşta hikmet verilen Hz. Yahya’nın Allah ve ailesiyle ilişkisi hangi niteliklerle anlatılır?',
    options: ['Allah katından şefkat ve arınmışlık sahibi, takva sahibi, anne babasına iyi davranan; zorba ve asi olmayan biri olarak', 'Yalnız siyasi gücüyle tanınan, anne babasından uzak ve sert bir hükümdar olarak', 'İbadeti gereksiz gören, toplumun geleneklerini vahyin önüne koyan biri olarak', 'Hata işlemeyen fakat insanlara hiçbir mesaj taşımayan melek tabiatlı bir varlık olarak'],
    correctIndex: 0,
    explanation: 'Meryem 12-15’te Hz. Yahya’ya çocukken hikmet verildiği, onun şefkatli, arınmış, takva sahibi ve anne babasına iyi davranan biri olduğu; zorba ve asi olmadığı bildirilir.',
    reference: 'Meryem 19/7-15',
  },
  {
    id: 286,
    category: 'Kıssa Bağlamı',
    question: 'Hz. Meryem doğum sancısıyla hurma ağacına yöneldiğinde kendisine verilen teselli ve pratik yönlendirmeler hangi seçenekte doğru biçimde bir araya getirilmiştir?',
    options: ['Üzülmemesi, altında bir su kaynağı oluşturulduğu, hurma dalını silkeleyerek taze hurma yemesi, içip gözünün aydın olması ve insanlarla konuşmama adağını bildirmesi söylenmiştir', 'Şehre dönüp bütün insanlara uzun bir savunma konuşması yapması ve hiç yiyecek almaması emredilmiştir', 'Çocuğu başka bir aileye bırakması, su kaynağından uzaklaşması ve olayı gizlemek için ülkeyi terk etmesi istenmiştir', 'Yalnız hurma ağacının altında beklemesi, hiçbir şey yiyip içmemesi ve ailesinden yardım istemesi emredilmiştir'],
    correctIndex: 0,
    explanation: 'Meryem 22-26’da doğum sancısı sırasında Hz. Meryem’e üzülmemesi, altında su bulunduğu, hurma dalını silkeleyip taze hurma yemesi ve gözünün aydın olması söylenir. İnsanla karşılaşırsa Rahman için susma adağında bulunduğunu belirtmesi istenir.',
    reference: 'Meryem 19/22-26',
  },
  {
    id: 287,
    category: 'Peygamberlik Delili',
    question: 'Hz. Meryem bebeği gösterdiğinde kavmin şaşkınlığına karşı Hz. İsa’nın beşikteki konuşması, kimliği ve görevi hakkında hangi temel bilgileri vermiştir?',
    options: ['Allah’ın kulu olduğunu, kendisine kitap verilip peygamber kılındığını, bulunduğu yerde bereketli yapıldığını ve yaşadığı sürece namazla zekâtın emredildiğini söylemiştir', 'Allah’ın oğlu olduğunu, hiçbir ibadetle sorumlu olmadığını ve yalnız hükümdarlık için geldiğini söylemiştir', 'Sadece annesini savunmuş, kendi peygamberliği ve kulluğu hakkında hiçbir açıklama yapmamıştır', 'Büyüyünce yeni bir ilah olacağını ve önceki peygamberlerin mesajlarını kaldıracağını söylemiştir'],
    correctIndex: 0,
    explanation: 'Meryem 29-33’te Hz. İsa ilk olarak Allah’ın kulu olduğunu ifade eder. Kitap, peygamberlik, bereket, namaz, zekât ve annesine iyi davranma niteliklerini sayarak hem annesini savunur hem de kendi konumunun kulluk olduğunu açıklar.',
    reference: 'Meryem 19/27-33',
  },
  {
    id: 288,
    category: 'Peygamberlere Destek',
    question: 'Hz. İsa İsrailoğullarının inkârcı tutumunu fark ettiğinde “Allah yolunda yardımcılarım kimlerdir?” diye sormuş, havariler buna nasıl cevap vermiştir?',
    options: ['Allah’ın yardımcıları olduklarını, Allah’a iman ettiklerini söylemiş ve Müslüman oluşlarına şahitlik edilmesini istemişlerdir', 'Yalnız maddi ücret verilirse yardım edeceklerini, inanç konusunda tarafsız kalacaklarını söylemişlerdir', 'Roma yönetiminden izin alınmadan hiçbir destek vermeyeceklerini ve tebliği bırakmasını istemişlerdir', 'Hz. İsa’yı ilah kabul ettiklerini ve Allah’a kulluğa gerek kalmadığını açıklamışlardır'],
    correctIndex: 0,
    explanation: 'Âl-i İmran 52-53’te havariler Allah’ın yardımcıları olduklarını, Allah’a iman ettiklerini ve teslim olanlardan sayılmak istediklerini bildirir. İndirilen mesaja ve elçiye iman ettiklerini söyleyerek şahitlerle birlikte yazılmayı dilerler.',
    reference: 'Âl-i İmran 3/52-53; Saff 61/14',
  },
  {
    id: 289,
    category: 'Siyer ve Vahiy',
    question: 'Kıblenin Mescid-i Aksa yönünden Mescid-i Haram yönüne çevrilmesi, Bakara suresinde Hz. Peygamber’in beklentisi ve ümmetin sınanması bakımından nasıl açıklanır?',
    options: ['Peygamberin yüzünü göğe çevirdiği görülmüş ve hoşnut olacağı kıbleye yöneltilmiş; önceki kıble ise peygambere uyanlarla geri dönenleri ayırt eden bir sınama olmuştur', 'Peygamber hiçbir yön değişikliği istememiş, karar yalnız Medineli tüccarların talebi üzerine alınmıştır', 'Kıble değişikliği namazın artık yönsüz kılınacağını ve Mescid-i Haram’ın önemini kaybettiğini göstermiştir', 'Önceki kıbleye yönelenlerin bütün ibadetlerinin geçersiz olduğu ve imanlarının kaybolduğu bildirilmiştir'],
    correctIndex: 0,
    explanation: 'Bakara 142-150’de kıble değişikliği eleştirilere cevapla birlikte anlatılır. Allah’ın doğu ve batının sahibi olduğu, önceki yönün bağlılığı sınadığı, Hz. Peygamber’in beklediği Mescid-i Haram yönünün belirlendiği ve geçmiş imanların boşa çıkarılmayacağı bildirilir.',
    reference: 'Bakara 2/142-150',
  },
  {
    id: 290,
    category: 'Peygamberin İbadeti',
    question: 'İsra suresinde Hz. Peygamber’e farz namazların yanında gecenin bir bölümünde yöneltilen özel ibadet emri ve bununla bağlantılı ümit nedir?',
    options: ['Kendisine mahsus ilave bir ibadet olarak teheccüd kılması ve Rabbinin onu övgüye değer bir makama yükseltmesinin umulmasıdır', 'Bütün gece hiç uyumadan yalnız dünya işleri hakkında düşünmesi ve hükümdar olmasıdır', 'Gündüz namazlarını bırakarak sadece gece ibadet etmesi ve insanlardan uzaklaşmasıdır', 'Gece ibadetini yalnız zenginlere öğretmesi ve diğer müminlerden gizlemesidir'],
    correctIndex: 0,
    explanation: 'İsra 78-79 gündüzün belli vakitleri ve sabah namazından sonra gecenin bir bölümünde Hz. Peygamber’e mahsus ek ibadet olarak teheccüdü emreder; bunun övgüye değer makam ümidiyle ilişkisini kurar.',
    reference: 'İsra 17/78-80',
  },
  {
    id: 291,
    category: 'Yönetim ve Ahlak',
    question: 'Uhud sonrasında Hz. Peygamber’in çevresindekilere karşı tutumu konusunda Âl-i İmran 159’da verilen liderlik ilkeleri hangi seçenekte eksiksizdir?',
    options: ['Allah’ın rahmetiyle yumuşak davranmak, onları affetmek, bağışlanmaları için dua etmek, işlerde danışmak ve karar verince Allah’a güvenmek', 'Hata yapan herkesi toplumdan çıkarmak, danışmayı bırakmak ve yalnız kişisel öfkeyle karar vermek', 'Savaşla ilgili bütün sorumluluğu başkalarına yüklemek ve bir daha hiçbir konuda görüş almamak', 'Yalnız başarılı kişileri affetmek, diğerlerinin tevbe etmesine imkân vermemek ve sonucu maddi güce bağlamak'],
    correctIndex: 0,
    explanation: 'Âl-i İmran 159, yenilgi ve hata sonrasında bile kaba ve katı olmamayı öğütler. Affetme, istiğfar, istişare, kararlılık ve tevekkül aynı liderlik bütününün parçaları olarak sunulur.',
    reference: 'Âl-i İmran 3/159',
  },
  {
    id: 292,
    category: 'Siyer ve Hüküm',
    question: 'Bedir esirleri hakkında Enfal suresinde yapılan uyarı, dünya menfaati ile savaşın hedefi arasındaki önceliği nasıl belirlemiş ve esirlere hangi umut kapısını açık bırakmıştır?',
    options: ['Yeryüzünde üstünlük sağlanmadan esir alıp fidye beklentisine ağırlık verilmesini eleştirmiş; esirlerin kalbinde hayır varsa Allah’ın kaybedilenden daha iyisini verip bağışlayacağını bildirmiştir', 'Her savaşta mümkün olduğu kadar çok esir almanın tek amaç olduğunu ve bağışlanmanın imkânsızlığını bildirmiştir', 'Esirlerin hiçbir şartta serbest bırakılamayacağını ve iman etmelerinin kabul edilmeyeceğini söylemiştir', 'Maddi kazancın ilahi rızadan her zaman üstün olduğunu ve savaşın yalnız ganimet için yapılacağını açıklamıştır'],
    correctIndex: 0,
    explanation: 'Enfal 67-70, sağlam bir üstünlük oluşmadan esir ve dünya malına yönelmeyi eleştirir. Bununla birlikte eldeki esirlere, Allah kalplerinde hayır bilirse alınandan daha iyisini vereceği ve onları bağışlayacağı mesajı iletilir.',
    reference: 'Enfal 8/67-71',
  },
  {
    id: 293,
    category: 'Siyer ve Tevbe',
    question: 'Tebük seferinin ağır şartlarında Hz. Peygamber’e uyan muhacir ve ensarın durumu ile geri kalan üç kişinin tevbesi, Tevbe suresinde hangi ortak ilahi rahmet çerçevesinde anlatılır?',
    options: ['Zorluk anında bazılarının kalpleri kaymaya yaklaşsa da Allah peygamberin ve ona uyanların tevbesini kabul etmiş; doğruluktan ayrılmayan üç kişiyi de sıkıntılı bekleyişten sonra bağışlamıştır', 'Seferden dönen herkes sorgusuz cezalandırılmış ve hiçbir tevbe kabul edilmemiştir', 'Yalnız maddi yardım yapanlar bağışlanmış, sefere fiilen katılanların imanları geçersiz sayılmıştır', 'Üç kişi mazeret uydurdukları için ödüllendirilmiş ve doğruluk göstermeleri gereksiz görülmüştür'],
    correctIndex: 0,
    explanation: 'Tevbe 117-119 zorluk seferinde Hz. Peygamber’e uyanların yaşadığı güçlüğü ve Allah’ın rahmetini anlatır. Geri kalan üç kişi yalan mazeret üretmeyip gerçeği söylediği için ağır bir toplumsal ve vicdani bekleyişin ardından tevbeleri kabul edilir; müminlere doğrularla beraber olma emredilir.',
    reference: 'Tevbe 9/117-119',
  },
  {
    id: 294,
    category: 'Siyer ve Vahiy',
    question: 'Hudeybiye sürecinde Hz. Peygamber’in Mescid-i Haram’a güven içinde girileceğine dair rüyası Fetih suresinde nasıl doğrulanmış ve gecikme nasıl açıklanmıştır?',
    options: ['Allah rüyanın gerçek olduğunu, müminlerin güven içinde saçlarını tıraş etmiş veya kısaltmış olarak mescide gireceğini bildirmiş; onların bilmediği yakın bir fethi önce vermiştir', 'Rüyanın gerçekleşmeyeceği, Mekke’ye girişin tamamen yasaklandığı ve barışın hiçbir yarar getirmediği bildirilmiştir', 'Rüyanın yalnız Hz. Peygamber’i ilgilendirdiği ve hiçbir müminin onunla birlikte giremeyeceği söylenmiştir', 'Mescid-i Haram’a giriş için tevhid inancından vazgeçilmesi ve müşriklerin bütün şartlarının kalıcı olarak kabulü istenmiştir'],
    correctIndex: 0,
    explanation: 'Fetih 27-28’de Allah’ın elçisine gösterdiği rüyayı doğruladığı, müminlerin güvenle Mescid-i Haram’a gireceği ve bunun öncesinde onların bilmediği yakın bir fetih verdiği açıklanır. Hudeybiye görünürde gecikme, gerçekte daha geniş imkânların başlangıcıdır.',
    reference: 'Fetih 48/27-28; Diyanet Kur’an Yolu Tefsiri',
  },
  {
    id: 295,
    category: 'Peygamber Ahlakı',
    question: 'Tevbe suresinin sonunda Hz. Muhammed’in ümmetine yönelik merhameti, onların sıkıntısı ve iman edenlerle ilişkisi bakımından nasıl tasvir edilir?',
    options: ['İçlerinden gelen bir elçi olarak sıkıntıya düşmeleri kendisine ağır gelen, onların iyiliğine çok düşkün, müminlere karşı şefkatli ve merhametli biri olarak', 'Toplumunun sıkıntılarına ilgisiz kalan, yalnız kendi ailesinin yararını gözeten bir hükümdar olarak', 'İnsanların iman edip etmemesini önemsemeyen ve hiçbir uyarı sorumluluğu bulunmayan biri olarak', 'Müminlere sert, düşmanlarına ise sınırsız taviz veren ve tebliğden uzak duran biri olarak'],
    correctIndex: 0,
    explanation: 'Tevbe 128, Hz. Peygamber’in insanî yakınlığını ve ümmet kaygısını yoğun ifadelerle açıklar. Sonraki ayet yüz çevirmeler karşısında Allah’a tevekkülü ve O’nun arşın Rabbi oluşunu hatırlatır.',
    reference: 'Tevbe 9/128-129',
  },
  {
    id: 296,
    category: 'Evrensel Risalet',
    question: 'Sebe 28’de Hz. Muhammed’in gönderiliş alanı ve tebliğinin iki temel yönü hangi ifadeyle belirlenir?',
    options: ['Bütün insanlara müjdeleyici ve uyarıcı olarak gönderildiği, fakat insanların çoğunun bunu bilmediği bildirilir', 'Yalnız Mekke’de yaşayan tek bir kabileye ekonomik düzen kurmak için gönderildiği bildirilir', 'Sadece önceki kitapları bilenlere hitap ettiği ve diğer toplumlara mesaj taşımadığı söylenir', 'Görevinin yalnız geçmiş peygamberlerin isimlerini saymakla sınırlı olduğu belirtilir'],
    correctIndex: 0,
    explanation: 'Sebe 28, Hz. Muhammed’in risaletini belirli bir kavimle sınırlamaz; bütün insanlara müjdeleyici ve uyarıcı olarak gönderildiğini açıklar. Bu evrensellik Enbiya 107’deki âlemlere rahmet oluşuyla da uyumludur.',
    reference: 'Sebe 34/28; Enbiya 21/107',
  },
  {
    id: 297,
    category: 'Peygamberlik Görevleri',
    question: 'Ahzab suresinde Hz. Peygamber’e art arda verilen görev nitelemeleri, tebliğin hangi boyutlarını bir araya getirir?',
    options: ['Şahit, müjdeleyici, uyarıcı, Allah’ın izniyle O’na çağıran ve ışık saçan bir kandil olma görevlerini', 'Yalnız savaş komutanlığı, vergi toplama ve siyasi sınırları genişletme görevlerini', 'İnsanların bütün tercihlerini zorla belirleme ve imanlarını kalplerine yerleştirme yetkisini', 'Gaybın tamamını bağımsız biçimde bilme ve ilahi hükmü değiştirme yetkisini'],
    correctIndex: 0,
    explanation: 'Ahzab 45-48, Hz. Peygamber’in şahitlik, müjde, uyarı ve Allah’a davet görevlerini “ışık saçan kandil” benzetmesiyle tamamlar. Görevin Allah’ın iznine bağlı olduğu vurgulanır; inkârcılara itaat etmemesi ve Allah’a güvenmesi istenir.',
    reference: 'Ahzab 33/45-48',
  },
  {
    id: 298,
    category: 'Peygamberlik Birliği',
    question: 'Enbiya suresine göre Hz. Muhammed’den önce gönderilen bütün peygamberlerin vahyinde değişmeden kalan temel inanç çağrısı nedir?',
    options: ['Allah’tan başka ilah bulunmadığı ve yalnız O’na kulluk edilmesi gerektiği çağrısıdır', 'Her toplumun kendi peygamberini ilah kabul etmesi gerektiği çağrısıdır', 'İbadetin yalnız belirli bir soya ait olduğu ve diğer insanların sorumlu olmadığı çağrısıdır', 'Sonraki peygamberlerin öncekilerin tevhid mesajını tamamen geçersiz kıldığı çağrısıdır'],
    correctIndex: 0,
    explanation: 'Enbiya 25, bütün peygamberlere “Benden başka ilah yoktur, bana kulluk edin” vahyinin verildiğini bildirir. Böylece farklı dönem ve hükümlere rağmen peygamberlik zincirinin tevhid merkezli birliği açıklanır.',
    reference: 'Enbiya 21/25; Nahl 16/36',
  },
  {
    id: 299,
    category: 'Peygamberlerin Beşerliği',
    question: 'Furkan suresinde önceki peygamberlerin günlük hayatları üzerinden, Hz. Muhammed’in yemek yemesi ve çarşılarda yürümesine yöneltilen itiraza nasıl cevap verilir?',
    options: ['Önceki elçilerin de yemek yiyen ve çarşılarda yürüyen insanlar olduğu, insanların birbirleri için bir sınama kılındığı ve sabrın beklendiği belirtilir', 'Gerçek peygamberlerin hiçbir zaman yemek yemediği ve toplum içine çıkmadığı kabul edilir', 'Hz. Muhammed’in beşer olmadığı, yalnız görünüşte insan gibi davrandığı söylenir', 'Peygamberliğin geçerli olması için mutlaka büyük hazine ve özel saray sahibi olmak gerektiği bildirilir'],
    correctIndex: 0,
    explanation: 'Furkan 7-20, müşriklerin peygamberin yemek yemesini ve çarşıda yürümesini küçümsemelerine cevap verir. Önceki elçilerin de aynı beşerî ihtiyaçlara sahip olduğu, peygamberliğin insan hayatından kopuk olmadığı ve bunun bir sabır sınaması olduğu açıklanır.',
    reference: 'Furkan 25/7-20',
  },
  {
    id: 300,
    category: 'Kur’an Kıssalarının Amacı',
    question: 'Hud suresinin sonunda peygamber kıssalarının Hz. Muhammed’e anlatılma amacı ve müminlere sağladığı ortak fayda hangi seçenekte doğru açıklanmıştır?',
    options: ['Peygamberin kalbini sağlamlaştırmak, gerçeği bildirmek ve müminlere öğütle hatırlatma sunmak için anlatılmıştır', 'Yalnız tarihî merakı gidermek ve hiçbir ahlaki sonuç çıkarmamak için anlatılmıştır', 'Geçmiş toplumların bütün günlük ayrıntılarını eksiksiz bir kronoloji hâlinde vermek için anlatılmıştır', 'Önceki peygamberlerin mesajlarının yanlış olduğunu göstermek ve aralarındaki bağı koparmak için anlatılmıştır'],
    correctIndex: 0,
    explanation: 'Hud 120, peygamber haberlerinin Hz. Peygamber’in kalbini pekiştirmek amacıyla anlatıldığını açıkça bildirir. Bu kıssalarla hakikat gelir; müminler için öğüt ve hatırlatma oluşur. Yusuf 111 de kıssalarda akıl sahipleri için ibret bulunduğunu belirtir.',
    reference: 'Hud 11/120; Yusuf 12/111',
  },
];
