export const KURAN_TESTI_SURE_SORULARI = [
  {
    id: 201,
    category: 'Ayet ve Meal',
    question: 'Hicr suresinde Kur’an’ın korunmasıyla ilgili verilen ilahi güvence hangisidir?',
    options: ['Kur’an’ı Allah’ın indirdiği ve onu yine Allah’ın koruyacağı', 'Kur’an’ın yalnız ezberleyenler tarafından korunacağı', 'Vahyin belirli bir dönemden sonra değiştirilebileceği', 'Kur’an’ın korunmasının sadece yazılı nüshalara bağlı olduğu'],
    correctIndex: 0,
    explanation: 'Hicr 9’da zikri, yani Kur’an’ı Allah’ın indirdiği ve onun koruyucusunun da Allah olduğu açıkça bildirilir.',
    reference: 'Hicr 15/9',
  },
  {
    id: 202,
    category: 'Ayet ve Meal',
    question: 'Zuhruf suresine göre Rahman’ın zikrini görmezden gelen kişiye nasıl bir sonuç bildirilir?',
    options: ['Kendisine yoldaş olacak bir şeytan musallat edilir', 'Dünya nimetlerinin tamamı hemen elinden alınır', 'İnsanlardan bütünüyle uzaklaştırılır', 'Hiçbir sorumluluğu kalmaz'],
    correctIndex: 0,
    explanation: 'Zuhruf 36-37, ilahi uyarıdan yüz çevirenin şeytanla yakınlık kuracağını ve bu yoldaşın onu doğru yolda olduğunu sanırken yoldan çıkaracağını anlatır.',
    reference: 'Zuhruf 43/36-37',
  },
  {
    id: 203,
    category: 'Ayet ve Meal',
    question: 'Duhan suresinin başında Kur’an’ın indirildiği zaman dilimi nasıl nitelenir?',
    options: ['Mübarek bir gece', 'Sıradan bir gündüz vakti', 'Yalnız savaşların yaşandığı bir ay', 'Güneş tutulmasının gerçekleştiği bir sabah'],
    correctIndex: 0,
    explanation: 'Duhan 3’te Kur’an’ın mübarek bir gecede indirildiği, bunun insanları uyarmaya yönelik ilahi hikmetin bir sonucu olduğu belirtilir.',
    reference: 'Duhan 44/1-6',
  },
  {
    id: 204,
    category: 'Ayet ve Meal',
    question: 'Ahkaf 15’te anne babaya iyilik emrinin ardından hamilelik ve sütten kesilme için toplam ne kadar süre zikredilir?',
    options: ['Otuz ay', 'On iki ay', 'Yirmi dört ay', 'Kırk ay'],
    correctIndex: 0,
    explanation: 'Ayet annenin çocuğu güçlükle taşıyıp doğurduğunu hatırlatır; hamilelik ve sütten kesilmenin toplamını otuz ay olarak bildirir.',
    reference: 'Ahkaf 46/15',
  },
  {
    id: 205,
    category: 'Ayet ve Meal',
    question: 'Zariyat suresinde cinlerin ve insanların yaratılış gayesi nasıl açıklanır?',
    options: ['Allah’a kulluk etmeleri', 'Yalnız dünya nimetlerini çoğaltmaları', 'Birbirleriyle üstünlük yarışı yapmaları', 'Yeryüzünde sınırsız güç toplamaları'],
    correctIndex: 0,
    explanation: 'Zariyat 56, cinlerin ve insanların Allah’a kulluk etmeleri için yaratıldığını bildirerek hayatın temel yönelişini ortaya koyar.',
    reference: 'Zariyat 51/56-58',
  },
  {
    id: 206,
    category: 'Tefekkür',
    question: 'Tur suresi yaratılışı inkâr edenlere hangi sarsıcı sorularla düşünme çağrısı yapar?',
    options: ['Hiçbir yaratıcı olmadan mı yaratıldılar, yoksa kendileri mi yaratıcıdır?', 'Neden bütün insanlar aynı servete sahip değildir?', 'Niçin yalnız gündüz vakti uyurlar?', 'Dağların yüksekliğini kim ölçmüştür?'],
    correctIndex: 0,
    explanation: 'Tur 35-36, insanın ve göklerle yerin sebepsiz ya da kendi kendine var olamayacağını sorgulatarak yaratıcıya iman üzerinde düşündürür.',
    reference: 'Tur 52/35-36',
  },
  {
    id: 207,
    category: 'Surelerin Mesajı',
    question: 'Rahman suresinde insanlara ve cinlere tekrar tekrar yöneltilen temel soru hangisidir?',
    options: ['Rabbinizin nimetlerinden hangisini inkâr edebilirsiniz?', 'Yeryüzünde kaç yıl kaldınız?', 'Hangi topluluk daha zengindir?', 'Gece mi gündüz mü daha uzundur?'],
    correctIndex: 0,
    explanation: 'Surede Allah’ın yaratma, ölçü, rızık, hesap ve cennet nimetleri anılır; “Rabbinizin nimetlerinden hangisini inkâr edebilirsiniz?” hitabı otuz bir kez tekrarlanır.',
    reference: 'Rahman 55/13 ve devamındaki tekrarlar',
  },
  {
    id: 208,
    category: 'Ahiret',
    question: 'Vakıa suresinin başında kıyamet sonrası insanlar hangi üç ana gruba ayrılır?',
    options: ['Ashab-ı meymene, ashab-ı meş’eme ve öne geçenler', 'Yalnız zenginler, fakirler ve yöneticiler', 'Çiftçiler, tüccarlar ve yolcular', 'Melekler, cinler ve insanlar'],
    correctIndex: 0,
    explanation: 'Vakıa 7-10’da insanlar sağın sahipleri, solun sahipleri ve hayırda öne geçenler şeklinde üç grupta ele alınır; sonraki ayetlerde sonuçları açıklanır.',
    reference: 'Vakıa 56/7-14',
  },
  {
    id: 209,
    category: 'Dünya ve Ahiret',
    question: 'Hadid 20’de dünya hayatının geçiciliği hangi özellikler dizisiyle anlatılır?',
    options: ['Oyun, eğlence, süs, övünme ve mal-evlat çoğaltma yarışı', 'Yalnız ilim, ibadet ve adalet', 'Sürekli mutluluk ve hiç bitmeyen güven', 'Hesabın ve sorumluluğun bulunmadığı kalıcı hayat'],
    correctIndex: 0,
    explanation: 'Ayet dünya hayatının aldatıcı yönlerini yağmurla yeşerip sonra kuruyan ekin örneğiyle açıklar; kalıcı değerin Allah’ın rızasında olduğunu hatırlatır.',
    reference: 'Hadid 57/20',
  },
  {
    id: 210,
    category: 'Ayet Bağlamı',
    question: 'Mücadele suresi adını, ilk ayetlerde Hz. Peygamberle konuşup durumunu Allah’a arz eden kadının hangi davranışından alır?',
    options: ['Eşi hakkında hakkını arayıp çözüm istemesinden', 'Mirasını gönüllü olarak terk etmesinden', 'Bir ticaret kervanına katılmasından', 'Şehirden ayrılmak istemesinden'],
    correctIndex: 0,
    explanation: 'Surenin başlangıcında eşi hakkında Hz. Peygamberle konuşan ve Allah’a şikâyette bulunan kadının sözüne Allah’ın karşılık verdiği bildirilir.',
    reference: 'Mücadele 58/1-4',
  },
  {
    id: 211,
    category: 'Toplumsal Ahlak',
    question: 'Mümtehine 8’e göre Müslümanlarla din uğruna savaşmayan ve onları yurtlarından çıkarmayan kimselere karşı nasıl davranılabilir?',
    options: ['İyilik ve adaletle', 'Her durumda düşmanlıkla', 'Haklarını gözetmeden', 'Onlarla hiçbir insani ilişki kurmadan'],
    correctIndex: 0,
    explanation: 'Ayet, savaşmayan ve sürgüne katılmayan kimselere iyilik yapmayı ve adil davranmayı yasaklamaz; Allah’ın adaletli davrananları sevdiğini bildirir.',
    reference: 'Mümtehine 60/8-9',
  },
  {
    id: 212,
    category: 'İbadet',
    question: 'Cuma suresine göre cuma günü namaz için çağrı yapıldığında müminlerden ne yapmaları istenir?',
    options: ['Allah’ı anmaya yönelip alışverişi bırakmaları', 'Ticareti hızlandırıp namazı ertelemeleri', 'Yalnız evlerinde dua etmeleri', 'Bütün gün çalışmayı bırakmaları'],
    correctIndex: 0,
    explanation: 'Cuma 9’da çağrı yapıldığında Allah’ı anmaya koşmak ve alışverişi bırakmak emredilir; namazdan sonra ise yeryüzüne dağılıp Allah’ın lütfunu aramaya izin verilir.',
    reference: 'Cuma 62/9-10',
  },
  {
    id: 213,
    category: 'Ahlak ve Sorumluluk',
    question: 'Münafikun suresi müminleri, hangi iki dünya nimetinin Allah’ı anmaktan alıkoymaması konusunda uyarır?',
    options: ['Mallar ve çocuklar', 'Evler ve bahçeler', 'Yağmur ve rüzgâr', 'Yolculuk ve ticaret'],
    correctIndex: 0,
    explanation: 'Münafikun 9, mal ve çocukların Allah’ı anmaktan uzaklaştırmaması gerektiğini; buna izin verenlerin gerçek kayba uğrayacağını bildirir.',
    reference: 'Münafikun 63/9-11',
  },
  {
    id: 214,
    category: 'Aile Ahlakı',
    question: 'Tegabun 14’te eşler ve çocuklarla ilgili uyarı, hangi bağışlayıcı tutumlarla dengelenir?',
    options: ['Affetmek, kusuru başa kakmamak ve bağışlamak', 'Aile bağlarını bütünüyle koparmak', 'Her hatayı toplum içinde açıklamak', 'Maddi desteği koşulsuz kesmek'],
    correctIndex: 0,
    explanation: 'Ayet bazı eş ve çocukların kişiyi doğru olandan alıkoyabileceğini söyleyerek dikkatli olmayı ister; ardından affetme ve bağışlamayı teşvik eder.',
    reference: 'Tegabun 64/14-15',
  },
  {
    id: 215,
    category: 'Tevekkül',
    question: 'Talak suresine göre Allah’a karşı sorumluluk bilinci taşıyan kişiye hangi iki imkân vaat edilir?',
    options: ['Bir çıkış yolu ve beklemediği yerden rızık', 'Sınırsız dünya serveti ve hiç hastalanmama', 'Her kararının sorgusuz doğru olması', 'Bütün sorumluluklarının kaldırılması'],
    correctIndex: 0,
    explanation: 'Talak 2-3, takva sahibine Allah’ın bir çıkış yolu göstereceğini ve onu ummadığı yerden rızıklandıracağını; tevekkül edene Allah’ın yeteceğini bildirir.',
    reference: 'Talak 65/2-3',
  },
  {
    id: 216,
    category: 'Peygamber Ahlakı',
    question: 'Kalem suresinde Hz. Muhammed’in kişiliği hangi güçlü ifadeyle övülür?',
    options: ['Sen elbette yüce bir ahlak üzeresin', 'Sen yalnız güçlü bir hükümdarsın', 'Sen dünya malını herkesten çok seversin', 'Sen insanlardan uzak yaşamalısın'],
    correctIndex: 0,
    explanation: 'Kalem 4, Hz. Peygamber’in ahlakını “yüce” olarak niteler; önceki ayetler onun Rabbinin nimeti sayesinde deli olmadığını da açıklar.',
    reference: 'Kalem 68/1-4',
  },
  {
    id: 217,
    category: 'İnsan ve Ahlak',
    question: 'Mearic suresinde eğitilmemiş insan tabiatının sıkıntı ve nimet karşısındaki iki tepkisi nasıl anlatılır?',
    options: ['Kötülük dokununca sızlanır, iyilik gelince cimrileşir', 'Her durumda sabırlı ve cömert olur', 'Sıkıntıyı fark etmez, nimeti paylaşır', 'Yalnız başkalarının sorunlarıyla ilgilenir'],
    correctIndex: 0,
    explanation: 'Mearic 19-21 insanın aceleci ve dayanıksız yönüne dikkat çeker; devamında namaz ve sorumluluk bilinci taşıyanların bu olumsuz özellikleri aştığı anlatılır.',
    reference: 'Mearic 70/19-35',
  },
  {
    id: 218,
    category: 'Peygamber Duası',
    question: 'Nuh suresinde Hz. Nuh, kavmine istiğfar etmelerinin ardından hangi nimetlerin verilebileceğini söyler?',
    options: ['Bol yağmur, mal, evlat, bahçeler ve ırmaklar', 'Yalnız siyasi güç ve askerî zafer', 'Hiç çalışmadan sınırsız servet', 'Ölümsüzlük ve sürekli gençlik'],
    correctIndex: 0,
    explanation: 'Hz. Nuh kavmini çok bağışlayıcı olan Rablerinden af dilemeye çağırır; yağmur, mal, evlat, bahçe ve ırmak nimetlerini sayar.',
    reference: 'Nuh 71/10-12',
  },
  {
    id: 219,
    category: 'Kur’an’ın Etkisi',
    question: 'Cin suresinin başında bir grup cin Kur’an’ı dinledikten sonra onu nasıl tanımlar?',
    options: ['Doğru yola ileten hayranlık verici bir Kur’an', 'Yalnız geçmiş olayları anlatan bir şiir', 'İnsanlara kapalı, anlaşılmaz bir metin', 'Sadece cinlere gönderilmiş bir kitap'],
    correctIndex: 0,
    explanation: 'Cinler Kur’an’ı dinleyince onun hayranlık uyandırdığını ve doğru yola ilettiğini söyler, ardından Rablerine ortak koşmayacaklarını açıklarlar.',
    reference: 'Cin 72/1-5',
  },
  {
    id: 220,
    category: 'Tebliğ',
    question: 'Müddessir suresinin ilk ayetlerinde vahiy görevi verilen Hz. Peygamber’e hangi emirler birlikte yöneltilir?',
    options: ['Kalkıp uyarmak, Rabbini yüceltmek, elbiseyi temiz tutmak ve kötülükten uzak durmak', 'Şehirden ayrılmak, ticareti bırakmak ve konuşmamak', 'Yalnız gece uyumak ve insanlarla görüşmemek', 'Sadece geçmiş kavimleri yazmak'],
    correctIndex: 0,
    explanation: 'Surenin başlangıcı bireysel hazırlığı toplumsal tebliğe bağlar: kalkıp uyarma, Rabbi yüceltme, temizlenme, kötülükten uzaklaşma ve sabır emirleri verilir.',
    reference: 'Müddessir 74/1-7',
  },
  {
    id: 221,
    category: 'Ahiret',
    question: 'Kıyame suresinde kıyamet günü bazı yüzlerin aydınlık olmasının sebebi neyle ilişkilendirilir?',
    options: ['Rablerine bakmalarıyla', 'Dünya servetlerini görmeleriyle', 'Soylarıyla övünmeleriyle', 'Hesaptan kaçmalarıyla'],
    correctIndex: 0,
    explanation: 'Kıyame 22-23’te bazı yüzlerin o gün ışıl ışıl olacağı ve Rablerine bakacağı bildirilir; sonraki ayetlerde bedbaht yüzlerin korkusu anlatılır.',
    reference: 'Kıyame 75/22-25',
  },
  {
    id: 222,
    category: 'Sure Üslubu',
    question: 'Mürselat suresinde farklı delil ve kıyamet sahnelerinin ardından tekrar edilen uyarı hangisidir?',
    options: ['O gün yalanlayanların vay haline!', 'Rabbinizin nimetlerinden hangisini inkâr edersiniz?', 'Her zorlukla beraber kolaylık vardır', 'Dininiz size, dinim banadır'],
    correctIndex: 0,
    explanation: '“O gün yalanlayanların vay haline!” uyarısı sure boyunca tekrar edilerek hesap gününü inkârın sonucu vurgulanır.',
    reference: 'Mürselat 77/15 ve devamındaki tekrarlar',
  },
  {
    id: 223,
    category: 'Ahiret',
    question: 'Nebe suresinin başındaki insanların hakkında anlaşmazlığa düştüğü “büyük haber” hangi ana gerçekle ilgilidir?',
    options: ['Öldükten sonra diriliş ve hesap', 'Yeni bir ticaret yolunun açılması', 'Bir hükümdarın tahta çıkışı', 'Mevsimlerin değişmesi'],
    correctIndex: 0,
    explanation: 'Surenin bütünü dikkate alındığında büyük haberin kıyamet, yeniden diriliş ve hesap olduğu anlaşılır; yaratılış delilleri bu gerçeğe kanıt olarak sunulur.',
    reference: 'Nebe 78/1-17',
  },
  {
    id: 224,
    category: 'Nefis Eğitimi',
    question: 'Naziat suresine göre Rabbinin huzurunda durmaktan korkup nefsini kötü arzudan uzaklaştıran kişinin varacağı yer neresidir?',
    options: ['Cennet', 'Dünyada sınırsız iktidar', 'Hesapsız bir ara bölge', 'Kavmine geri dönüş'],
    correctIndex: 0,
    explanation: 'Naziat 40-41, Allah’ın huzurunda hesap verme bilinciyle nefsini kötü arzudan alıkoyan kişinin barınağının cennet olduğunu bildirir.',
    reference: 'Naziat 79/37-41',
  },
  {
    id: 225,
    category: 'Tebliğ Ahlakı',
    question: 'Abese suresinin başlangıcındaki uyarı, tebliğde hangi önceliğin gözetilmesi gerektiğini öğretir?',
    options: ['Samimiyetle öğrenmek isteyen kişinin toplumsal konumuna bakılmadan önemsenmesi', 'Yalnız zengin ve güçlü kişilere zaman ayrılması', 'Görme engellilerin eğitimden uzak tutulması', 'İnsanların niyetlerinin kesin olarak bilinebileceği'],
    correctIndex: 0,
    explanation: 'Sure, görme engelli Abdullah b. Ümmü Mektum’un öğrenme isteği karşısında yüzünü ekşitme olayını ele alır; samimi arayışın makamdan üstün olduğunu öğretir.',
    reference: 'Abese 80/1-10',
  },
  {
    id: 226,
    category: 'Kıyamet',
    question: 'Tekvir suresinde kıyamet sahnelerinin sonunda her insanın neyi kesin olarak bileceği bildirilir?',
    options: ['Önceden hazırlayıp getirdiği amelleri', 'Başkalarının bütün gizli düşüncelerini', 'Dünyaya yeniden kaç kez döneceğini', 'Hangi kavimden olduğunu'],
    correctIndex: 0,
    explanation: 'Güneşin dürülmesi, yıldızların sönmesi ve kayıtların açılması gibi sahnelerden sonra her nefsin ne hazırlayıp getirdiğini bileceği söylenir.',
    reference: 'Tekvir 81/1-14',
  },
  {
    id: 227,
    category: 'Ticaret Ahlakı',
    question: 'Mutaffifin suresinde “ölçü ve tartıda hile yapanlar” hangi çifte standart nedeniyle kınanır?',
    options: ['Alırken tam ölçüp başkalarına verirken eksiltmeleri', 'Her alışverişte eşit davranmaları', 'Fakirlere karşılıksız yardım etmeleri', 'Ürünlerini tartmadan bağışlamaları'],
    correctIndex: 0,
    explanation: 'Surenin ilk ayetleri kendi haklarını tam isteyen, fakat başkasına ölçüp tartarken eksiltenleri ağır biçimde uyarır ve diriliş gününü hatırlatır.',
    reference: 'Mutaffifin 83/1-6',
  },
  {
    id: 228,
    category: 'Ahiret',
    question: 'İnşikak suresine göre amel defteri sağ tarafından verilen kişi nasıl bir hesapla karşılaşır?',
    options: ['Kolay bir hesapla', 'Sonsuz bir sorguyla', 'Hiçbir ameli görülmeden', 'Başkasının günahlarıyla'],
    correctIndex: 0,
    explanation: 'Defteri sağından verilen kişinin kolayca hesaba çekileceği ve sevinçle yakınlarına döneceği; arkasından verilenin ise helak isteyeceği anlatılır.',
    reference: 'İnşikak 84/7-15',
  },
  {
    id: 229,
    category: 'İman ve Sabır',
    question: 'Büruc suresindeki “hendek sahipleri” müminlere hangi sebeple işkence etmiştir?',
    options: ['Güçlü ve övgüye layık Allah’a iman ettikleri için', 'Ticaret anlaşmasını reddettikleri için', 'Şehirden göç etmek istemedikleri için', 'Yeni bir vergi koydukları için'],
    correctIndex: 0,
    explanation: 'Ateş dolu hendeklerin başında oturan zalimler, müminlerden yalnız Allah’a iman ettikleri için intikam almıştır; sure iman uğruna sabrı öne çıkarır.',
    reference: 'Büruc 85/4-10',
  },
  {
    id: 230,
    category: 'İnsan ve Sorumluluk',
    question: 'Tarık suresinde her insanla ilgili bildirilen gözetim gerçeği hangisidir?',
    options: ['Üzerinde mutlaka bir gözetleyici bulunduğu', 'Hiçbir davranışının kaydedilmediği', 'Yalnız gündüz yaptıklarının bilindiği', 'Soyunun onu hesaptan kurtaracağı'],
    correctIndex: 0,
    explanation: 'Tarık 4, hiçbir kimsenin üzerinde bir gözetleyici bulunmaksızın bırakılmadığını bildirir; ardından insanı yaratılışı üzerinde düşünmeye çağırır.',
    reference: 'Tarık 86/1-8',
  },
  {
    id: 231,
    category: 'Tefekkür',
    question: 'Gaşiye suresinde insanın yaratılış ve çevre üzerinde düşünmesi için hangi dört varlığa bakması istenir?',
    options: ['Deve, gök, dağlar ve yeryüzü', 'Deniz, balık, ay ve yıldızlar', 'Arı, karınca, kuş ve ağaç', 'Güneş, yağmur, nehir ve gemi'],
    correctIndex: 0,
    explanation: 'Ayetler devenin yaratılışına, göğün yükseltilişine, dağların dikilişine ve yeryüzünün yayılışına dikkat çekerek tefekküre çağırır.',
    reference: 'Gaşiye 88/17-20',
  },
  {
    id: 232,
    category: 'Ahiret',
    question: 'Fecr suresinin sonunda huzura ermiş nefse hangi çağrı yapılır?',
    options: ['Rabbine razı olmuş ve razı olunmuş olarak dön; kullarımın arasına ve cennetime gir', 'Dünyaya dönüp servetini artır', 'Hesaptan kaçmak için uzaklaş', 'Yalnız başına yeni bir hayat kur'],
    correctIndex: 0,
    explanation: 'Surenin sonunda “ey huzura kavuşmuş nefis” hitabıyla Allah’tan razı ve Allah’ın razı olduğu hâlde dönüş, kulların arasına ve cennete giriş müjdelenir.',
    reference: 'Fecr 89/27-30',
  },
  {
    id: 233,
    category: 'Toplumsal Sorumluluk',
    question: 'Beled suresinde “sarp yokuşu aşmak” hangi somut iyilik örnekleriyle açıklanır?',
    options: ['Köle azat etmek veya kıtlık gününde yakını olan yetimi ve yoksulu doyurmak', 'Yalnız çok mal biriktirip saymak', 'İnsanlardan uzaklaşıp hiçbir sorumluluk almamak', 'Gücünü göstermek için servet harcamak'],
    correctIndex: 0,
    explanation: 'Sure gerçek zorlu aşamayı özgürleştirme, açlık zamanında yetimi ve yoksulu doyurma; ardından iman, sabır ve merhamet tavsiyesiyle açıklar.',
    reference: 'Beled 90/11-18',
  },
  {
    id: 234,
    category: 'Nefis Eğitimi',
    question: 'Şems suresinde nefsini arındıran ve onu kötülüğe gömen kişiler için hangi karşıt sonuç bildirilir?',
    options: ['Arındıran kurtulur, kötülüğe gömen kaybeder', 'Her ikisi de aynı sonucu alır', 'Yalnız servet sahibi olan kurtulur', 'Nefsin tercihlerinin hiçbir sonucu yoktur'],
    correctIndex: 0,
    explanation: 'Şems 9-10 insanın ahlaki eğitim ve tercih sorumluluğunu özlü biçimde verir: nefsi arındırmak kurtuluş, onu günaha gömmek kayıptır.',
    reference: 'Şems 91/7-10',
  },
  {
    id: 235,
    category: 'İnfak ve Ahlak',
    question: 'Leyl suresinde malını verip Allah’a karşı sorumluluk taşıyan ve en güzeli doğrulayan kişiye neyin kolaylaştırılacağı bildirilir?',
    options: ['En kolay ve güzel yolun', 'Sınırsız dünya iktidarının', 'Hiç çalışmadan zenginliğin', 'Başkalarının hesabını görmenin'],
    correctIndex: 0,
    explanation: 'Veren, takva sahibi olan ve en güzeli doğrulayan kişiye kolay yol; cimrilik edip kendini yeterli görene ise zorlu yolun kolaylaştırılacağı belirtilir.',
    reference: 'Leyl 92/5-11',
  },
  {
    id: 236,
    category: 'Peygamberlik',
    question: 'Duha suresinde Hz. Peygamber’e geçmişte verilen hangi üç ilahi destek hatırlatılır?',
    options: ['Yetimken barındırılma, yol ararken doğruya yöneltilme ve ihtiyaç içindeyken yeterli kılınma', 'Hükümdarlık, büyük ordu ve saray', 'Uzun ömür, sınırsız servet ve hastalıksız hayat', 'Denizlerin açılması, rüzgârın yönetilmesi ve demirin yumuşaması'],
    correctIndex: 0,
    explanation: 'Duha 6-8, Hz. Peygamber’in yetimken korunmasını, yol arayışında hidayete ulaştırılmasını ve ihtiyaçtan kurtarılmasını hatırlatır; ardından yetim ve yoksula iyi davranma emredilir.',
    reference: 'Duha 93/6-11',
  },
  {
    id: 237,
    category: 'Ümit ve Sabır',
    question: 'İnşirah suresinde zorluk karşısında iki kez tekrarlanan temel müjde hangisidir?',
    options: ['Şüphesiz zorlukla beraber bir kolaylık vardır', 'Her zorluk insanı mutlaka yenilgiye götürür', 'Kolaylık yalnız dünyadaki zenginliktir', 'Sorumluluktan kaçmak huzur getirir'],
    correctIndex: 0,
    explanation: 'İnşirah 5-6’da zorlukla beraber kolaylığın bulunduğu iki kez vurgulanır; ardından bir işi bitirince yenisine yönelmek ve yalnız Rabbe rağbet etmek istenir.',
    reference: 'İnşirah 94/5-8',
  },
  {
    id: 238,
    category: 'Yaratılış',
    question: 'Tin suresinde insanın yaratılışı ve değerini koruması hangi dengeyle anlatılır?',
    options: ['En güzel biçimde yaratılır; iman edip iyi işler yapanlar aşağı düşüşten korunur', 'Doğuştan değersizdir ve hiçbir davranış bunu değiştirmez', 'Yalnız bedensel güç insanın değerini belirler', 'İnsan yaptıklarından hiçbir zaman sorumlu değildir'],
    correctIndex: 0,
    explanation: 'İnsan en güzel kıvamda yaratılmıştır; aşağıların aşağısına dönüşün karşısına iman edip salih amel işleyenlerin kesintisiz ödülü konur.',
    reference: 'Tin 95/4-6',
  },
  {
    id: 239,
    category: 'Kur’an Bilgisi',
    question: 'Kadir suresine göre Kadir gecesinin değeri nasıl ifade edilir?',
    options: ['Bin aydan daha hayırlıdır', 'Tam olarak yüz güne eşittir', 'Yalnız geçmiş ümmetlere aittir', 'Sadece gündüz ibadetinden değerlidir'],
    correctIndex: 0,
    explanation: 'Kadir gecesinin bin aydan hayırlı olduğu, meleklerin ve Ruh’un Rablerinin izniyle indiği ve gecenin tan yerinin ağarmasına kadar esenlik olduğu bildirilir.',
    reference: 'Kadir 97/1-5',
  },
  {
    id: 240,
    category: 'İbadet',
    question: 'Beyyine suresinde insanlara emredilen “dosdoğru din” hangi temel davranışlarla açıklanır?',
    options: ['Dini Allah’a özgüleyerek kulluk etmek, namazı kılmak ve zekâtı vermek', 'Yalnız soyla övünmek ve servet toplamak', 'İbadeti gösteriş için yapmak', 'Toplumsal sorumluluklardan kaçınmak'],
    correctIndex: 0,
    explanation: 'Beyyine 5 samimi kulluğu, hanif yönelişi, namazı ve zekâtı dosdoğru dinin temel göstergeleri olarak birlikte sayar.',
    reference: 'Beyyine 98/5',
  },
  {
    id: 241,
    category: 'Ahiret',
    question: 'Zilzal suresine göre insanın yaptığı iyilik ve kötülüklerin değerlendirilmesinde ne kadar küçük bir miktar bile karşılıksız kalmaz?',
    options: ['Zerre ağırlığı kadar', 'Bir dağ büyüklüğü kadar', 'Yalnız toplumun gördüğü kadar', 'Sadece yazılı olarak bildirilen kadar'],
    correctIndex: 0,
    explanation: 'Sure, yeryüzünün haberlerini anlatacağı hesap gününde zerre kadar iyilik veya kötülük yapanın onu göreceğini bildirir.',
    reference: 'Zilzal 99/6-8',
  },
  {
    id: 242,
    category: 'İnsan ve Ahlak',
    question: 'Adiyat suresinde hızla koşan atların canlı tasvirinden sonra insanın hangi ahlaki zaafına dikkat çekilir?',
    options: ['Rabbine karşı çok nankör oluşuna ve mal sevgisinin kuvvetine', 'Her durumda cömert ve sabırlı oluşuna', 'Bilgiye hiç ihtiyaç duymamasına', 'Yalnız yolculuktan korkmasına'],
    correctIndex: 0,
    explanation: 'İlk ayetlerde koşan atlar anlatılır; ardından insanın Rabbine karşı nankörlüğü, buna kendisinin şahitliği ve mala aşırı sevgisi eleştirilir.',
    reference: 'Adiyat 100/1-11',
  },
  {
    id: 243,
    category: 'Ahiret',
    question: 'Karia suresine göre kıyamet gününde tartıları ağır gelenle hafif gelenin sonuçları nasıl ayrılır?',
    options: ['Ağır gelen hoşnut bir hayata, hafif gelen Haviye’ye gider', 'Her ikisi de aynı karşılığı görür', 'Hafif gelen doğrudan dünyaya döner', 'Ağır gelen hesaba alınmaz fakat ödül de almaz'],
    correctIndex: 0,
    explanation: 'Karia 6-11, amel tartısı ağır gelen için hoşnut bir hayatı; hafif gelen için kızgın ateş olarak açıklanan Haviye’yi bildirir.',
    reference: 'Karia 101/6-11',
  },
  {
    id: 244,
    category: 'Dünya ve Ahiret',
    question: 'Tekasür suresine göre insanı mezarlara varıncaya kadar oyalayan temel tutku nedir?',
    options: ['Çoklukla övünme ve çoğaltma yarışı', 'İlim öğrenme arzusu', 'Yoksullara yardım etme isteği', 'Aile bağlarını koruma çabası'],
    correctIndex: 0,
    explanation: 'Tekasür, daha çok mal, güç veya taraftar edinme yarışının ölümü unutturmasını eleştirir ve nimetlerden mutlaka sorgulanılacağını bildirir.',
    reference: 'Tekasür 102/1-8',
  },
  {
    id: 245,
    category: 'Ahlak',
    question: 'Hümeze suresinde ağır biçimde kınanan kişi tipi hangi davranışları bir arada taşır?',
    options: ['İnsanları çekiştirip ayıplar, mal yığıp sayar ve servetinin kendisini ebedileştireceğini sanır', 'Malını paylaşır ve insanları onurlandırır', 'Sözünü doğrular ve emaneti korur', 'Yetimi gözetip yoksulu doyurur'],
    correctIndex: 0,
    explanation: 'Sure sözle veya davranışla insanları küçümseyen, servetini güvence ve ebedilik aracı sanan kişiyi Hutame azabıyla uyarır.',
    reference: 'Hümeze 104/1-9',
  },
  {
    id: 246,
    category: 'Kur’an Kıssası',
    question: 'Fil suresinde Kâbe’ye saldıran fil ordusunun planının boşa çıkarılması hangi olayla anlatılır?',
    options: ['Üzerlerine pişmiş balçıktan taşlar atan sürü sürü kuşların gönderilmesiyle', 'Denizin ikiye ayrılmasıyla', 'Şiddetli bir tufanın başlamasıyla', 'Ordunun kendi isteğiyle şehri terk etmesiyle'],
    correctIndex: 0,
    explanation: 'Allah fil ordusunun tuzağını boşa çıkarmış, üzerlerine taşlar atan kuşlar göndermiş ve onları yenilip çiğnenmiş ekine çevirmiştir.',
    reference: 'Fil 105/1-5',
  },
  {
    id: 247,
    category: 'Şükür ve Kulluk',
    question: 'Kureyş suresinde kış ve yaz yolculuklarıyla güven ve rızık verilen Kureyş’e hangi görev hatırlatılır?',
    options: ['Bu evin, yani Kâbe’nin Rabbine kulluk etmeleri', 'Yolculukları tamamen bırakmaları', 'Rızkı yalnız kendi güçlerinden bilmeleri', 'Kâbe’yi ticarete kapatmaları'],
    correctIndex: 0,
    explanation: 'Kureyş’in ticari yolculuklarla kazandığı düzen, açlıktan doyurulma ve korkudan güvene erişme nimetleri Kâbe’nin Rabbine kullukla ilişkilendirilir.',
    reference: 'Kureyş 106/1-4',
  },
  {
    id: 248,
    category: 'İbadet ve Ahlak',
    question: 'Maun suresine göre dini yalanlayan kişinin toplumsal davranışları arasında hangileri bulunur?',
    options: ['Yetimi itip kakmak, yoksulu doyurmaya teşvik etmemek ve küçük yardımları esirgemek', 'Yetimi koruyup yoksulu doyurmak', 'İbadette samimi ve yardımda cömert olmak', 'Komşularının bütün ihtiyaçlarını gözetmek'],
    correctIndex: 0,
    explanation: 'Sure dini yalanlamayı yalnız sözlü inkârla sınırlamaz; yetime ve yoksula duyarsızlık, gösterişçi namaz ve küçük yardımları engellemekle ilişkilendirir.',
    reference: 'Maun 107/1-7',
  },
  {
    id: 249,
    category: 'Şükür ve İbadet',
    question: 'Kevser suresinde Hz. Peygamber’e verilen büyük nimetin ardından hangi iki ibadet emredilir?',
    options: ['Rabbi için namaz kılmak ve kurban kesmek', 'Oruç tutmak ve yolculuğa çıkmak', 'Yalnız susmak ve inzivaya çekilmek', 'Ticareti bırakmak ve mal biriktirmek'],
    correctIndex: 0,
    explanation: 'Kevser nimeti karşısında namaz ve kurban yalnız Rabbe yöneltilir; Hz. Peygamber’e kin tutanın asıl soyu kesik olduğu bildirilir.',
    reference: 'Kevser 108/1-3',
  },
  {
    id: 250,
    category: 'Tevhid',
    question: 'Kafirun suresi inanç ve ibadet konusunda hangi temel tavizsizliği ifade eder?',
    options: ['Allah’a kulluğun şirkle uzlaştırılamayacağını ve herkesin tercihinin sorumluluğunu taşıdığını', 'Bütün inançların ibadet biçimlerinin aynı olduğunu', 'Dönüşümlü olarak putlara da ibadet edilebileceğini', 'Tevhidin yalnız belirli günlerde geçerli olduğunu'],
    correctIndex: 0,
    explanation: 'Sure Hz. Peygamber’in müşriklerin ibadet ettiği varlıklara ibadet etmeyeceğini tekrarlar ve “Sizin dininiz size, benim dinim bana” diyerek tevhidde uzlaşmazlığı açıklar.',
    reference: 'Kafirun 109/1-6',
  },
  {
    id: 251,
    category: 'Siyer ve Ayet',
    question: 'Nasr suresinde Allah’ın yardımı ve fetih gelip insanların topluluklar hâlinde dine girdiği görüldüğünde Hz. Peygamber’e ne yapması emredilir?',
    options: ['Rabbini hamd ile tesbih etmek ve O’ndan bağışlanma dilemek', 'Zaferle övünüp insanları küçümsemek', 'Tebliği tamamen bırakıp servet toplamak', 'Geçmiş hataları başkalarına yüklemek'],
    correctIndex: 0,
    explanation: 'Nasr suresi başarı karşısında kibir yerine hamd, tesbih ve istiğfar öğretir; Allah’ın tövbeleri çokça kabul ettiği hatırlatılır.',
    reference: 'Nasr 110/1-3',
  },
  {
    id: 252,
    category: 'Siyer ve Ayet',
    question: 'Tebbet suresinde Hz. Peygamber’e açıkça düşmanlık eden hangi kişi ve eşi uyarılır?',
    options: ['Ebu Leheb ve odun taşıyıcısı olarak nitelenen eşi', 'Ebu Talib ve eşi', 'Hz. Hamza ve eşi', 'Ebu Bekir ve eşi'],
    correctIndex: 0,
    explanation: 'Sure Ebu Leheb’in servetinin kendisine fayda vermeyeceğini, kendisinin ve eziyete ortak olan eşinin sonuçla karşılaşacağını bildirir.',
    reference: 'Tebbet 111/1-5',
  },
  {
    id: 253,
    category: 'Dua ve Sığınma',
    question: 'Felak suresinde Allah’a sığınılması öğretilen kötülükler hangi seçenekte birlikte verilmiştir?',
    options: ['Yaratılmışların şerri, karanlık çöktüğündeki şer, düğümlere üfleyenler ve kıskananın şerri', 'Yalnız doğal afetler ve yolculuk', 'Sadece maddi yoksulluk ve hastalık', 'Bilgi öğrenmek ve çalışmak'],
    correctIndex: 0,
    explanation: 'Felak suresi dışarıdan gelebilecek genel ve özel kötülüklere karşı sabahın Rabbine sığınmayı öğretir.',
    reference: 'Felak 113/1-5',
  },
  {
    id: 254,
    category: 'Dua ve Sığınma',
    question: 'Nas suresinde insanların kalplerine vesvese veren sinsi kötülükten, Allah’ın hangi üç sıfatına sığınılır?',
    options: ['İnsanların Rabbi, hükümdarı ve ilahı oluşuna', 'Yalnız yaratıcı ve rızık verici oluşuna', 'Sadece bağışlayıcı ve sabırlı oluşuna', 'Geceyi ve gündüzü yaratmış oluşuna'],
    correctIndex: 0,
    explanation: 'Nas suresi Allah’ı insanların Rabbi, meliki ve ilahı olarak anarak cinlerden ve insanlardan gelen sinsi vesveseye karşı O’na sığınmayı öğretir.',
    reference: 'Nas 114/1-6',
  },
];
